# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: emsdb
    restart: always
    environment:
      POSTGRES_PASSWORD: emsdb

  adminer:
    image: emsdb
    restart: always
    ports:
      - 8889:8889